---
repo: AdobeDocs/commerce-admin.en
url: https://experienceleague.adobe.com/en/docs/commerce-admin/user-guides/home
exclude:
  - Rakefile
  - tmp
  - Gemfile
  - Gemfile.lock
kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]